name: scrapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_scrapper.txt
          
      - name: execute python workflows
        run: python scrapper.py

      - name: commit and push
        run: |
          git config --global user.email "rudolfnosek.rn@gmail.com"
          git add data/huntington.csv
          git config --global user.name "Automatic"
          git commit -m "Scrapper - Auto commit "
          git push